### ISSUE TITLE
Checklist contains invalid hyperlink

### ISSUE THREAD

**Issue by stefanov-stefan** [dotnet/home#73] opened 2017-03-30 10:52 UTC
The [checklist](https://github.com/dotnet/home/blob/master/guidance/new-projects.md) contains a link to  http://ivantomic.com/projects/ospnc/ which is unreachable.

**Comment by svick** [comment] 2017-03-30 11:34
This issue is a duplicate of https://github.com/dotnet/home/issues/72.

**Comment by jongalloway** [comment] 2017-03-31 16:49
Closing as duplicate of #72

**Closed by jongalloway** 2017-03-31 16:49 UTC
